### ISSUE TITLE
ArgumentError: PartialTensorShape: Incompatible shapes during merge: [720,1280,3] vs. [720,1140,3]

### ISSUE THREAD

**Issue by pavelxx1** [BrehmiumPwr/deblurring_ntire2020#2]
Hi!
I have this error after run train phase
my all train image size is 1280x720 

```
/deblurring_ntire2020
2020-07-13 22:41:34.073987: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 22:41:35.835786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-13 22:41:35.858139: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:35.858771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2020-07-13 22:41:35.858809: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 22:41:35.860425: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 22:41:35.862026: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-13 22:41:35.862387: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-13 22:41:35.864244: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-13 22:41:35.865479: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-13 22:41:35.869248: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 22:41:35.869378: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:35.869967: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:35.870489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
 [*] Found 1 videos
 [**] Found 110 frames in video datasets/REDS_MotionBlur/train_blur/train/train_blur/000001/
2020-07-13 22:41:35.880396: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200000000 Hz
2020-07-13 22:41:35.880673: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3005100 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-13 22:41:35.880708: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-13 22:41:35.974437: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:35.975382: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x30052c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-13 22:41:35.975418: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2020-07-13 22:41:35.975618: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:35.976201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla P100-PCIE-16GB computeCapability: 6.0
coreClock: 1.3285GHz coreCount: 56 deviceMemorySize: 15.90GiB deviceMemoryBandwidth: 681.88GiB/s
2020-07-13 22:41:35.976236: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 22:41:35.976322: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 22:41:35.976350: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-13 22:41:35.976371: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-13 22:41:35.976395: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-13 22:41:35.976418: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-13 22:41:35.976440: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 22:41:35.976519: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:35.977136: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:35.977701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-13 22:41:35.977755: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 22:41:36.495317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-13 22:41:36.495376: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-07-13 22:41:36.495390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-07-13 22:41:36.495646: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:36.496543: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-13 22:41:36.497226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14974 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)
 [*] Found 1 videos
 [**] Found 19 frames in video datasets/REDS_MotionBlur/val_blur/val/val_blur/000001/
 [*] Loading model from None
0it [00:00, ?it/s]2020-07-13 22:41:53.391744: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 22:41:54.460412: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
loss_g: 0.3340, loss_d: 0.0000: : 0it [00:18, ?it/s]
validating: 0it [00:00, ?it/s]
validating: 1it [00:17, 17.29s/it]
validating: 2it [00:18,  9.16s/it]

calculating scores:   0% 0/2 [00:00<?, ?it/s]
calculating scores: 100% 2/2 [00:00<00:00,  3.81it/s]
SSIM: 0.10, PSNR: 7.53
loss_g: 0.2682, loss_d: 0.0000: : 6it [00:41,  6.97s/it]2020-07-13 22:42:18.912887: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at list_kernels.h:101 : Invalid argument: PartialTensorShape: Incompatible shapes during merge: [720,1280,3] vs. [720,1140,3]
loss_g: 3.9631, loss_d: 0.0000: : 7it [00:41,  4.93s/it]2020-07-13 22:42:19.096423: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at list_kernels.h:101 : Invalid argument: PartialTensorShape: Incompatible shapes during merge: [720,1280,3] vs. [720,1140,3]
loss_g: 0.4934, loss_d: 0.0000: : 8it [00:41,  3.51s/it]2020-07-13 22:42:19.294278: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at list_kernels.h:101 : Invalid argument: PartialTensorShape: Incompatible shapes during merge: [720,1280,3] vs. [720,1140,3]
loss_g: 0.7946, loss_d: 0.0000: : 23it [00:44,  5.15it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1986, in execution_mode
    yield
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 655, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2363, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 6653, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: PartialTensorShape: Incompatible shapes during merge: [720,1280,3] vs. [720,1140,3]
	 [[{{node map_1/TensorArrayV2Stack/TensorListStack}}]] [Op:IteratorGetNext]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 43, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 35, in main
    train.build_model(FLAGS)
  File "/deblurring_ntire2020/train.py", line 117, in build_model
    train(dataset_train_g, model, dataset_val, checkpoint_manager_ssim, checkpoint_manager_psnr, output_path)
  File "/deblurring_ntire2020/train.py", line 130, in train
    for train_datapoint_g in pbar:
  File "/usr/local/lib/python3.6/dist-packages/tqdm/std.py", line 1104, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 631, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 670, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 661, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 1989, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: PartialTensorShape: Incompatible shapes during merge: [720,1280,3] vs. [720,1140,3]
	 [[{{node map_1/TensorArrayV2Stack/TensorListStack}}]]
2020-07-13 22:42:22.495106: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
loss_g: 0.7946, loss_d: 0.0000: : 23it [00:45,  1.96s/it]
```

**Comment by BrehmiumPwr** [comment]
You should check your images. We expect them to be 720x1280x3. If, in any case, you might want to use images of a different size, you will have to do some changes to the dataset code
